{
  "results": [
    {
      "bathrooms": 2,
      "bedrooms": 3,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "SINGLE_FAMILY",
      "imgSrc": "https://photos.zillowstatic.com/fp/5f3904c58b17657a259069356277a04e-p_e.jpg",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.701239,
      "listing_sub_type": {
        "is_FSBA": true
      },
      "livingArea": 2298,
      "longitude": -95.35417,
      "lotAreaUnit": "sqft",
      "lotAreaValue": 5000,
      "price": 375000,
      "priceForHDP": 375000,
      "rentZestimate": 1979,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "5920 Conley St",
      "taxAssessedValue": 301316,
      "zestimate": 261600,
      "zipcode": "77021",
      "zpid": 80513508
    },
    {
      "bathrooms": 2,
      "bedrooms": 3,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "SINGLE_FAMILY",
      "imgSrc": "https://maps.googleapis.com/maps/api/staticmap?mobile=false&sensor=true&maptype=satellite&size=575x242&zoom=17&center=29.84433937072754,-95.37059020996094&key=AIzaSyBJsNQO5ZeG-XAbqqWLKwG08fWITSxg33w&signature=kcZLOrfeUqlEX6M7GwUAePLJ2c0=",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.84434,
      "listing_sub_type": {
        "is_FSBA": true
      },
      "livingArea": 2822,
      "longitude": -95.37059,
      "lotAreaUnit": "acres",
      "lotAreaValue": 0.3257,
      "price": 349900,
      "priceForHDP": 349900,
      "rentZestimate": 2149,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "324 Wynell St",
      "taxAssessedValue": 279602,
      "zestimate": 300200,
      "zipcode": "77022",
      "zpid": 27955153
    },
    {
      "bathrooms": 3,
      "bedrooms": 3,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "datePriceChanged": 1671091200000,
      "daysOnZillow": -1,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "SINGLE_FAMILY",
      "imgSrc": "https://photos.zillowstatic.com/fp/ff5d9781fd61c57085f7dc9428c93f28-p_e.jpg",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.866304,
      "listing_sub_type": {
        "is_FSBA": true
      },
      "livingArea": 2444,
      "longitude": -95.656395,
      "lotAreaUnit": "sqft",
      "lotAreaValue": 5379.66,
      "price": 309990,
      "priceChange": -40010,
      "priceForHDP": 309990,
      "priceReduction": "$40,010 (Dec 15)",
      "rentZestimate": 2120,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "6123 Crown Hill Ln",
      "taxAssessedValue": 282149,
      "zestimate": 350000,
      "zipcode": "77084",
      "zpid": 62587903
    },
    {
      "bathrooms": 0,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "datePriceChanged": 1671091200000,
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "LOT",
      "imgSrc": "https://maps.googleapis.com/maps/api/staticmap?mobile=false&sensor=true&maptype=satellite&size=575x242&zoom=17&center=29.67613983154297,-95.24182891845703&key=AIzaSyBJsNQO5ZeG-XAbqqWLKwG08fWITSxg33w&signature=YZIb-n5N3xUI_DCoASSPg4MjWWg=",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.67614,
      "listing_sub_type": {
        "is_FSBA": true
      },
      "longitude": -95.24183,
      "lotAreaUnit": "acres",
      "lotAreaValue": 1.2063,
      "price": 64999,
      "priceChange": -1,
      "priceForHDP": 64999,
      "priceReduction": "$1 (Dec 15)",
      "rentZestimate": 1030,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "5427 N Crooked Creek Dr",
      "taxAssessedValue": 16266,
      "zipcode": "77017",
      "zpid": 97605694
    },
    {
      "bathrooms": 4,
      "bedrooms": 3,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "datePriceChanged": 1671091200000,
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "SINGLE_FAMILY",
      "imgSrc": "https://maps.googleapis.com/maps/api/staticmap?mobile=false&sensor=true&maptype=satellite&size=575x242&zoom=17&center=29.77690315246582,-95.37516021728516&key=AIzaSyBJsNQO5ZeG-XAbqqWLKwG08fWITSxg33w&signature=fIRjrmE7TJGlpvB6cZXRenMxoIw=",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.776903,
      "listing_sub_type": {
        "is_FSBA": true
      },
      "livingArea": 2222,
      "longitude": -95.37516,
      "lotAreaUnit": "sqft",
      "lotAreaValue": 1622,
      "price": 485000,
      "priceChange": 484515,
      "priceForHDP": 485000,
      "rentZestimate": 3300,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "2205 Colorado St",
      "taxAssessedValue": 434137,
      "zestimate": 489000,
      "zipcode": "77007",
      "zpid": 124873951
    },
    {
      "bathrooms": 2,
      "bedrooms": 4,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "datePriceChanged": 1671091200000,
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "SINGLE_FAMILY",
      "imgSrc": "https://maps.googleapis.com/maps/api/staticmap?mobile=false&sensor=true&maptype=satellite&size=575x242&zoom=17&center=29.633407592773438,-95.27283477783203&key=AIzaSyBJsNQO5ZeG-XAbqqWLKwG08fWITSxg33w&signature=_3pXRxG8jd6IWRLCqkT2JUNWvJA=",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.633408,
      "listing_sub_type": {
        "is_FSBA": true
      },
      "livingArea": 2768,
      "longitude": -95.272835,
      "lotAreaUnit": "acres",
      "lotAreaValue": 0.5395,
      "price": 549999,
      "priceChange": -25000,
      "priceForHDP": 549999,
      "priceReduction": "$25,000 (Dec 15)",
      "rentZestimate": 2395,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "8223 Jet Pilot St",
      "taxAssessedValue": 562687,
      "zestimate": 562800,
      "zipcode": "77075",
      "zpid": 97637150
    },
    {
      "bathrooms": 0,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "datePriceChanged": 1671091200000,
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "LOT",
      "imgSrc": "https://photos.zillowstatic.com/fp/94399b8aab00c9ad3540fe935649ae70-p_e.jpg",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "listing_sub_type": {
        "is_FSBA": true
      },
      "lotAreaUnit": "acres",
      "lotAreaValue": 0.3099,
      "price": 135000,
      "priceChange": 90000,
      "priceForHDP": 135000,
      "rentZestimate": 1295,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "0 Norwich St",
      "zipcode": "77028",
      "zpid": 2071107459
    },
    {
      "bathrooms": 4,
      "bedrooms": 3,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "daysOnZillow": -1,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "SINGLE_FAMILY",
      "imgSrc": "https://photos.zillowstatic.com/fp/7a0f08b3ea716b1d34cc50ce494563cb-p_e.jpg",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.76584,
      "listing_sub_type": {
        "is_FSBA": true
      },
      "livingArea": 3530,
      "longitude": -95.59333,
      "lotAreaUnit": "sqft",
      "lotAreaValue": 8637.948,
      "price": 825000,
      "priceForHDP": 825000,
      "rentZestimate": 4924,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "554 Rancho Bauer Dr",
      "taxAssessedValue": 789555,
      "zestimate": 818700,
      "zipcode": "77079",
      "zpid": 27986396
    },
    {
      "bathrooms": 0,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "LOT",
      "imgSrc": "https://maps.googleapis.com/maps/api/staticmap?mobile=false&sensor=true&maptype=satellite&size=575x242&zoom=17&center=29.87543296813965,-95.45124053955078&key=AIzaSyBJsNQO5ZeG-XAbqqWLKwG08fWITSxg33w&signature=o3ajw_s16IJqXuvgZs2BtNtMe5o=",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.875433,
      "listing_sub_type": {
        "is_FSBA": true
      },
      "longitude": -95.45124,
      "lotAreaUnit": "sqft",
      "lotAreaValue": 2748.636,
      "price": 40000,
      "priceForHDP": 40000,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "1 Sunnyhill St",
      "zipcode": "77088",
      "zpid": 2060516890
    },
    {
      "bathrooms": 6,
      "bedrooms": 5,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "SINGLE_FAMILY",
      "imgSrc": "https://photos.zillowstatic.com/fp/945187c5b0ae61df3e270ac230f5211a-p_e.jpg",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.779339,
      "listing_sub_type": {
        "is_FSBA": true
      },
      "livingArea": 4793,
      "longitude": -95.55573,
      "lotAreaUnit": "sqft",
      "lotAreaValue": 8624.88,
      "price": 1850000,
      "priceForHDP": 1850000,
      "rentZestimate": 11720,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "12635 Rocky Meadow Dr",
      "taxAssessedValue": 1563090,
      "zestimate": 1845100,
      "zipcode": "77024",
      "zpid": 28095034
    },
    {
      "bathrooms": 2,
      "bedrooms": 3,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "TOWNHOUSE",
      "imgSrc": "https://maps.googleapis.com/maps/api/staticmap?mobile=false&sensor=true&maptype=satellite&size=575x242&zoom=17&center=29.701717376708984,-95.59262084960938&key=AIzaSyBJsNQO5ZeG-XAbqqWLKwG08fWITSxg33w&signature=7nl3ODPQeDJ1WsBbehWfO0Msy3w=",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.701717,
      "listing_sub_type": {
        "is_FSBA": true
      },
      "livingArea": 1208,
      "longitude": -95.59262,
      "lotAreaUnit": "sqft",
      "lotAreaValue": 4586,
      "price": 172300,
      "priceForHDP": 172300,
      "rentZestimate": 1537,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "7008 Jetty Ln",
      "taxAssessedValue": 131350,
      "zestimate": 141900,
      "zipcode": "77072",
      "zpid": 28142347
    },
    {
      "bathrooms": 2,
      "bedrooms": 3,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "MULTI_FAMILY",
      "imgSrc": "https://photos.zillowstatic.com/fp/7b49325f2259530333316445b93ce849-p_e.jpg",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.877378,
      "listing_sub_type": {
        "is_newHome": true
      },
      "livingArea": 2300,
      "longitude": -95.425835,
      "lotAreaUnit": "sqft",
      "lotAreaValue": 3600,
      "newConstructionType": "NEW_CONSTRUCTION_TYPE_OTHER",
      "price": 399999,
      "priceForHDP": 399999,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "1017 N Lane St",
      "zipcode": "77088",
      "zpid": 2060402039
    },
    {
      "bathrooms": 2,
      "bedrooms": 2,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "TOWNHOUSE",
      "imgSrc": "https://photos.zillowstatic.com/fp/f6c7dfdf95a9235e7e5c8bcbd251bd13-p_e.jpg",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.687956,
      "listing_sub_type": {
        "is_FSBA": true
      },
      "livingArea": 1088,
      "longitude": -95.58082,
      "lotAreaUnit": "sqft",
      "lotAreaValue": 2336,
      "price": 84900,
      "priceForHDP": 84900,
      "rentZestimate": 1394,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "11525 Beechnut St",
      "taxAssessedValue": 93220,
      "zestimate": 132000,
      "zipcode": "77072",
      "zpid": 28134525
    },
    {
      "bathrooms": 2,
      "bedrooms": 3,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "datePriceChanged": 1671091200000,
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "SINGLE_FAMILY",
      "imgSrc": "https://photos.zillowstatic.com/fp/2d37a3b5086ab0090b0b0d743c0b6e02-p_e.jpg",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.987602,
      "listing_sub_type": {
        "is_newHome": true
      },
      "livingArea": 1857,
      "longitude": -95.52496,
      "lotAreaUnit": "sqft",
      "lotAreaValue": 7736.256,
      "newConstructionType": "BUILDER_SPEC",
      "price": 398000,
      "priceChange": -10000,
      "priceForHDP": 398000,
      "priceReduction": "$10,000 (Dec 15)",
      "rentZestimate": 1948,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "13848 Paradise Valley Dr",
      "taxAssessedValue": 72507,
      "zestimate": 402500,
      "zipcode": "77069",
      "zpid": 27804259
    },
    {
      "bathrooms": 2,
      "bedrooms": 3,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "SINGLE_FAMILY",
      "imgSrc": "https://maps.googleapis.com/maps/api/staticmap?mobile=false&sensor=true&maptype=satellite&size=575x242&zoom=17&center=29.8920955657959,-95.48091125488281&key=AIzaSyBJsNQO5ZeG-XAbqqWLKwG08fWITSxg33w&signature=7Gw__7nI3D_NZY-SpBuURtyP-nE=",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.892096,
      "listing_sub_type": {
        "is_FSBA": true
      },
      "livingArea": 1828,
      "longitude": -95.48091,
      "lotAreaUnit": "sqft",
      "lotAreaValue": 6298.776,
      "price": 199900,
      "priceForHDP": 199900,
      "rentZestimate": 1749,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "8534 Parkhill Forest Dr",
      "taxAssessedValue": 209375,
      "zestimate": 226000,
      "zipcode": "77088",
      "zpid": 28266341
    },
    {
      "bathrooms": 3,
      "bedrooms": 4,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "SINGLE_FAMILY",
      "imgSrc": "https://photos.zillowstatic.com/fp/9b7f49dc2fc42c14adf3d7a89b8b37cb-p_e.jpg",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.806288,
      "listing_sub_type": {
        "is_FSBA": true
      },
      "livingArea": 2446,
      "longitude": -95.38363,
      "lotAreaUnit": "sqft",
      "lotAreaValue": 3598.056,
      "price": 849900,
      "priceForHDP": 849900,
      "rentZestimate": 4694,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "922 Adele St",
      "taxAssessedValue": 625498,
      "zestimate": 774700,
      "zipcode": "77009",
      "zpid": 124874049
    },
    {
      "bathrooms": 3,
      "bedrooms": 3,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "datePriceChanged": 1668067200000,
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "SINGLE_FAMILY",
      "imgSrc": "https://photos.zillowstatic.com/fp/62cff21a03ecf97cff2f3953323e47d6-p_e.jpg",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.78878,
      "listing_sub_type": {
        "is_FSBA": true
      },
      "livingArea": 2863,
      "longitude": -95.48989,
      "lotAreaUnit": "acres",
      "lotAreaValue": 0.3444,
      "price": 1099990,
      "priceChange": -30010,
      "priceForHDP": 1099990,
      "priceReduction": "$30,010 (Nov 10)",
      "rentZestimate": 6803,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "8206 Mallie Ct",
      "taxAssessedValue": 1181593,
      "zestimate": 1052164,
      "zipcode": "77055",
      "zpid": 27953831
    },
    {
      "bathrooms": 2,
      "bedrooms": 3,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "datePriceChanged": 1671091200000,
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "MULTI_FAMILY",
      "imgSrc": "https://photos.zillowstatic.com/fp/6fc7ae919ed7a9665b8e181c2970305b-p_e.jpg",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "listing_sub_type": {
        "is_newHome": true
      },
      "livingArea": 2300,
      "lotAreaUnit": "sqft",
      "lotAreaValue": 5625,
      "newConstructionType": "NEW_CONSTRUCTION_TYPE_OTHER",
      "price": 369999,
      "priceChange": -15001,
      "priceForHDP": 369999,
      "priceReduction": "$15,001 (Dec 15)",
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "8715 Bertwood St",
      "zipcode": "77016",
      "zpid": 2061145326
    },
    {
      "bathrooms": 3,
      "bedrooms": 2,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "TOWNHOUSE",
      "imgSrc": "https://photos.zillowstatic.com/fp/96ceedba529837949a4ce0e34d454a39-p_e.jpg",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.793642,
      "listing_sub_type": {
        "is_FSBA": true
      },
      "livingArea": 1386,
      "longitude": -95.547104,
      "lotAreaUnit": "sqft",
      "lotAreaValue": 2101,
      "price": 185000,
      "priceForHDP": 185000,
      "rentZestimate": 1800,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "10197 Beekman Place Dr",
      "taxAssessedValue": 154356,
      "zestimate": 179400,
      "zipcode": "77043",
      "zpid": 28167008
    },
    {
      "bathrooms": 2,
      "bedrooms": 4,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "SINGLE_FAMILY",
      "imgSrc": "https://photos.zillowstatic.com/fp/f15bb054bfcab4d682c16c97cb440841-p_e.jpg",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.849607,
      "listing_sub_type": {
        "is_FSBA": true
      },
      "livingArea": 1916,
      "longitude": -95.63158,
      "lotAreaUnit": "sqft",
      "lotAreaValue": 6777.936,
      "price": 285000,
      "priceForHDP": 285000,
      "rentZestimate": 1999,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "15618 Oldridge Dr",
      "taxAssessedValue": 269127,
      "zestimate": 282425,
      "zipcode": "77084",
      "zpid": 28262355
    },
    {
      "bathrooms": 2,
      "bedrooms": 3,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "SINGLE_FAMILY",
      "imgSrc": "https://photos.zillowstatic.com/fp/7d9956b7b59491bbf397a7e67dc8552b-p_e.jpg",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 30.016829,
      "listing_sub_type": {
        "is_FSBA": true
      },
      "livingArea": 2144,
      "longitude": -95.457146,
      "lotAreaUnit": "sqft",
      "lotAreaValue": 8359.164,
      "price": 205000,
      "priceForHDP": 205000,
      "rentZestimate": 1947,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "17282 Beaver Springs Dr",
      "taxAssessedValue": 204676,
      "zestimate": 237300,
      "zipcode": "77090",
      "zpid": 28206715
    },
    {
      "bathrooms": 0,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "daysOnZillow": -1,
      "group_type": "BUILDER_COMMUNITY",
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "SINGLE_FAMILY",
      "imgSrc": "https://photos.zillowstatic.com/fp/afa65e8da8e53eca94694e664f7bdce4-p_e.jpg",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": true,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.96644,
      "listing_sub_type": {
        "is_newHome": true
      },
      "longitude": -95.44473,
      "newConstructionType": "BUILDER_PLAN",
      "price": 0,
      "priceForHDP": 0,
      "priceSuffix": "+",
      "providerListingID": "29888846",
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "Homes Available Soon Plan, Legacy Park",
      "unit": "# UGM237",
      "zipcode": "77067",
      "zpid": 2060402534
    },
    {
      "bathrooms": 3,
      "bedrooms": 3,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "daysOnZillow": -1,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "TOWNHOUSE",
      "imgSrc": "https://photos.zillowstatic.com/fp/ec7990e9e4b6441040988223b42f797a-p_e.jpg",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.842066,
      "listing_sub_type": {
        "is_FSBA": true,
        "is_openHouse": true
      },
      "livingArea": 1802,
      "longitude": -95.4161,
      "lotAreaUnit": "sqft",
      "lotAreaValue": 2009,
      "openHouse": "Sat. 1-3pm",
      "open_house_info": {
        "open_house_showing": [
          {
            "open_house_end": 1671318000000,
            "open_house_start": 1671310800000
          }
        ]
      },
      "price": 309000,
      "priceForHDP": 309000,
      "rentZestimate": 2499,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "5246 Brinkman Ct",
      "taxAssessedValue": 265754,
      "zestimate": 300900,
      "zipcode": "77091",
      "zpid": 97621524
    },
    {
      "bathrooms": 3,
      "bedrooms": 4,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "daysOnZillow": -1,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "SINGLE_FAMILY",
      "imgSrc": "https://photos.zillowstatic.com/fp/bc8cedf8b10d48e06082ff057cc276f7-p_e.jpg",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.566736,
      "listing_sub_type": {
        "is_FSBA": true,
        "is_openHouse": true
      },
      "livingArea": 2003,
      "longitude": -95.14231,
      "lotAreaUnit": "sqft",
      "lotAreaValue": 7910.496,
      "openHouse": "Sat. 12-2pm",
      "open_house_info": {
        "open_house_showing": [
          {
            "open_house_end": 1671314400000,
            "open_house_start": 1671307200000
          }
        ]
      },
      "price": 365000,
      "priceForHDP": 365000,
      "rentZestimate": 2214,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "405 Chedworth Dr",
      "taxAssessedValue": 310000,
      "zestimate": 368000,
      "zipcode": "77062",
      "zpid": 28319666
    },
    {
      "bathrooms": 1,
      "bedrooms": 1,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "CONDO",
      "imgSrc": "https://photos.zillowstatic.com/fp/14ce855c1df4eaa7f3680f0367349902-p_e.jpg",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.754206,
      "listing_sub_type": {
        "is_FSBA": true
      },
      "livingArea": 718,
      "longitude": -95.45839,
      "lotAreaUnit": "acres",
      "lotAreaValue": 2.9447,
      "price": 135000,
      "priceForHDP": 135000,
      "rentZestimate": 1415,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "800 Post Oak Blvd APT 96",
      "taxAssessedValue": 147048,
      "unit": "Apt 96",
      "zestimate": 147400,
      "zipcode": "77056",
      "zpid": 28289284
    },
    {
      "bathrooms": 1,
      "bedrooms": 3,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "SINGLE_FAMILY",
      "imgSrc": "https://photos.zillowstatic.com/fp/2f009577ebd747ed6793fb72e154e7df-p_e.jpg",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.821981,
      "listing_sub_type": {
        "is_FSBA": true
      },
      "livingArea": 1124,
      "longitude": -95.44863,
      "lotAreaUnit": "sqft",
      "lotAreaValue": 10323.72,
      "price": 335000,
      "priceForHDP": 335000,
      "rentZestimate": 1924,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "2103 Woodcrest Dr",
      "taxAssessedValue": 413276,
      "zestimate": 377000,
      "zipcode": "77018",
      "zpid": 27912838
    },
    {
      "bathrooms": 2,
      "bedrooms": 1,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "CONDO",
      "imgSrc": "https://photos.zillowstatic.com/fp/dfa603c702208ecdd2a8fabe37f9f0e4-p_e.jpg",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.694635,
      "listing_sub_type": {
        "is_FSBA": true
      },
      "livingArea": 1174,
      "longitude": -95.391426,
      "lotAreaUnit": "acres",
      "lotAreaValue": 4.2565,
      "price": 174999,
      "priceForHDP": 174999,
      "rentZestimate": 1800,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "7575 Cambridge St APT 802",
      "taxAssessedValue": 150897,
      "unit": "Apt 802",
      "zestimate": 166000,
      "zipcode": "77054",
      "zpid": 28440892
    },
    {
      "bathrooms": 2,
      "bedrooms": 2,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "TOWNHOUSE",
      "imgSrc": "https://maps.googleapis.com/maps/api/staticmap?mobile=false&sensor=true&maptype=satellite&size=575x242&zoom=17&center=29.650856018066406,-95.50502014160156&key=AIzaSyBJsNQO5ZeG-XAbqqWLKwG08fWITSxg33w&signature=E5DCotL4LbZhSCOC5Xq-u8lJQQw=",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.650856,
      "listing_sub_type": {
        "is_FSBA": true
      },
      "livingArea": 1440,
      "longitude": -95.50502,
      "lotAreaUnit": "sqft",
      "lotAreaValue": 1968,
      "price": 138000,
      "priceForHDP": 138000,
      "rentZestimate": 1649,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "6479 Cambridge Glen Ln",
      "taxAssessedValue": 80095,
      "zestimate": 117000,
      "zipcode": "77035",
      "zpid": 28322865
    },
    {
      "bathrooms": 4,
      "bedrooms": 4,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "SINGLE_FAMILY",
      "imgSrc": "https://photos.zillowstatic.com/fp/37cdd0f1f654a7a229e139126a4df86e-p_e.jpg",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.693686,
      "listing_sub_type": {
        "is_newHome": true
      },
      "livingArea": 4303,
      "longitude": -95.43771,
      "lotAreaUnit": "sqft",
      "lotAreaValue": 7500,
      "newConstructionType": "BUILDER_SPEC",
      "price": 1850000,
      "priceForHDP": 1850000,
      "rentZestimate": 6499,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "3814 Tartan Ln",
      "taxAssessedValue": 641142,
      "zipcode": "77025",
      "zpid": 27985020
    },
    {
      "bathrooms": 3,
      "bedrooms": 4,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "datePriceChanged": 1671091200000,
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "SINGLE_FAMILY",
      "imgSrc": "https://photos.zillowstatic.com/fp/9eddfe9ea85951320024acc17f604f55-p_e.jpg",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.68258,
      "listing_sub_type": {
        "is_FSBA": true
      },
      "livingArea": 2690,
      "longitude": -95.678894,
      "lotAreaUnit": "sqft",
      "lotAreaValue": 5797.836,
      "price": 345000,
      "priceChange": 20000,
      "priceForHDP": 345000,
      "rentZestimate": 2549,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "8422 Fredericksburg Ln",
      "taxAssessedValue": 205000,
      "zestimate": 325000,
      "zipcode": "77083",
      "zpid": 59756213
    },
    {
      "bathrooms": 3,
      "bedrooms": 4,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "SINGLE_FAMILY",
      "imgSrc": "https://photos.zillowstatic.com/fp/255cfa6e69fd8d515e6163056a548f02-p_e.jpg",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.712456,
      "listing_sub_type": {
        "is_FSBA": true
      },
      "livingArea": 2750,
      "longitude": -95.4386,
      "lotAreaUnit": "sqft",
      "lotAreaValue": 4351.644,
      "price": 1195000,
      "priceForHDP": 1195000,
      "rentZestimate": 6465,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "3820 Byron St",
      "taxAssessedValue": 930099,
      "zestimate": 1049999,
      "zipcode": "77005",
      "zpid": 27823374
    },
    {
      "bathrooms": 0,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "LOT",
      "imgSrc": "https://photos.zillowstatic.com/fp/c362b52408c621077a74af388465b6ae-p_e.jpg",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.686615,
      "listing_sub_type": {
        "is_FSBA": true
      },
      "longitude": -95.372894,
      "lotAreaUnit": "sqft",
      "lotAreaValue": 5000.688,
      "price": 139000,
      "priceForHDP": 139000,
      "rentZestimate": 1800,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "3518 Seabrook St",
      "taxAssessedValue": 90000,
      "zipcode": "77021",
      "zpid": 305336890
    },
    {
      "bathrooms": 2,
      "bedrooms": 3,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "datePriceChanged": 1669795200000,
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "SINGLE_FAMILY",
      "imgSrc": "https://photos.zillowstatic.com/fp/d1e506b0e65f2f9ee179d2a521b7d34c-p_e.jpg",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.690134,
      "listing_sub_type": {
        "is_FSBA": true
      },
      "livingArea": 1600,
      "longitude": -95.29503,
      "lotAreaUnit": "sqft",
      "lotAreaValue": 6577.56,
      "price": 235000,
      "priceChange": -2990,
      "priceForHDP": 235000,
      "priceReduction": "$2,990 (Nov 30)",
      "rentZestimate": 1764,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "7397 Fairway Dr",
      "taxAssessedValue": 143015,
      "zestimate": 226020,
      "zipcode": "77087",
      "zpid": 80528453
    },
    {
      "bathrooms": 2,
      "bedrooms": 2,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "CONDO",
      "imgSrc": "https://photos.zillowstatic.com/fp/412e99393bb555ce0ba885b90484a278-p_e.jpg",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.69615,
      "listing_sub_type": {
        "is_FSBA": true
      },
      "livingArea": 1177,
      "longitude": -95.41051,
      "lotAreaUnit": "acres",
      "lotAreaValue": 3.7163,
      "price": 159950,
      "priceForHDP": 159950,
      "rentZestimate": 1813,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "2211 S Braeswood Blvd APT 23G",
      "taxAssessedValue": 156393,
      "unit": "Apt 23G",
      "zestimate": 171300,
      "zipcode": "77030",
      "zpid": 28429825
    },
    {
      "bathrooms": 1,
      "bedrooms": 1,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "CONDO",
      "imgSrc": "https://photos.zillowstatic.com/fp/59e10c340685c2f8e67cc75d3b30dbae-p_e.jpg",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.760153,
      "listing_sub_type": {
        "is_FSBA": true
      },
      "livingArea": 580,
      "longitude": -95.39988,
      "lotAreaUnit": "acres",
      "lotAreaValue": 2.9873,
      "price": 225000,
      "priceForHDP": 225000,
      "rentZestimate": 1500,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "3231 Allen Pkwy APT 1208",
      "taxAssessedValue": 157475,
      "unit": "Apt 1208",
      "zestimate": 191500,
      "zipcode": "77019",
      "zpid": 68427143
    },
    {
      "bathrooms": 0,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "LOT",
      "imgSrc": "https://photos.zillowstatic.com/fp/00ba51ea6300119c8460a04645f0339a-p_e.jpg",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.61964,
      "listing_sub_type": {
        "is_FSBA": true
      },
      "longitude": -95.36035,
      "lotAreaUnit": "sqft",
      "lotAreaValue": 7875.648,
      "price": 68000,
      "priceForHDP": 68000,
      "rentZestimate": 1737,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "13016 Donegal Way",
      "taxAssessedValue": 39375,
      "zipcode": "77047",
      "zpid": 97663318
    },
    {
      "bathrooms": 3,
      "bedrooms": 4,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "datePriceChanged": 1671091200000,
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "SINGLE_FAMILY",
      "imgSrc": "https://photos.zillowstatic.com/fp/a40f2a94677f1b88d87fb076f98dd2c1-p_e.jpg",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.985426,
      "listing_sub_type": {
        "is_FSBA": true
      },
      "livingArea": 2330,
      "longitude": -95.449615,
      "lotAreaUnit": "sqft",
      "lotAreaValue": 4399.56,
      "price": 260000,
      "priceChange": -10000,
      "priceForHDP": 260000,
      "priceReduction": "$10,000 (Dec 15)",
      "rentZestimate": 2005,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "1743 York Creek Dr",
      "taxAssessedValue": 268587,
      "zestimate": 278800,
      "zipcode": "77014",
      "zpid": 121113826
    },
    {
      "bathrooms": 3,
      "bedrooms": 3,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "daysOnZillow": -1,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "SINGLE_FAMILY",
      "imgSrc": "https://photos.zillowstatic.com/fp/60279951648f0a0fc10c4b17204bb57f-p_e.jpg",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.793842,
      "listing_sub_type": {
        "is_bankOwned": true,
        "is_openHouse": true
      },
      "livingArea": 2433,
      "longitude": -95.43067,
      "lotAreaUnit": "sqft",
      "lotAreaValue": 2774.772,
      "openHouse": "Sat. 12-3pm",
      "open_house_info": {
        "open_house_showing": [
          {
            "open_house_end": 1671318000000,
            "open_house_start": 1671307200000
          }
        ]
      },
      "price": 409900,
      "priceForHDP": 409900,
      "rentZestimate": 3127,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "1323 Ella Pl",
      "taxAssessedValue": 401932,
      "zestimate": 413300,
      "zipcode": "77008",
      "zpid": 80595028
    },
    {
      "bathrooms": 2,
      "bedrooms": 4,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "daysOnZillow": 0,
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "SINGLE_FAMILY",
      "imgSrc": "https://photos.zillowstatic.com/fp/30cee5fa1b39458a0d4ecc89acd525f9-p_e.jpg",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": false,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.853619,
      "listing_sub_type": {
        "is_FSBA": true
      },
      "livingArea": 1790,
      "longitude": -95.3736,
      "lotAreaUnit": "sqft",
      "lotAreaValue": 7200.468,
      "price": 210000,
      "priceForHDP": 210000,
      "rentZestimate": 1765,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "254 Tallant St",
      "taxAssessedValue": 210242,
      "zestimate": 215700,
      "zipcode": "77076",
      "zpid": 27941046
    },
    {
      "bathrooms": 2,
      "bedrooms": 4,
      "city": "Houston",
      "country": "USA",
      "currency": "USD",
      "datePriceChanged": 1670486400000,
      "daysOnZillow": -1,
      "group_type": "BUILDER_COMMUNITY",
      "homeStatus": "FOR_SALE",
      "homeStatusForHDP": "FOR_SALE",
      "homeType": "SINGLE_FAMILY",
      "imgSrc": "https://photos.zillowstatic.com/fp/62c89f8b44fb7786ae6e61621b3db1ad-p_e.jpg",
      "isFeatured": false,
      "isNonOwnerOccupied": true,
      "isPreforeclosureAuction": false,
      "isPremierBuilder": true,
      "isUnmappable": false,
      "isZillowOwned": false,
      "latitude": 29.62513,
      "listing_sub_type": {
        "is_newHome": true
      },
      "livingArea": 2385,
      "longitude": -95.37648,
      "newConstructionType": "BUILDER_PLAN",
      "price": 349990,
      "priceChange": -19000,
      "priceForHDP": 349990,
      "priceReduction": "$19,000 (Dec 8)",
      "priceSuffix": "+",
      "providerListingID": "29834604",
      "rentZestimate": 1709,
      "shouldHighlight": false,
      "state": "TX",
      "streetAddress": "Sally Plan, City Gate",
      "unit": "# O7J5VY",
      "zipcode": "77047",
      "zpid": 2061468469
    }
  ],
  "resultsPerPage": 40,
  "totalPages": 20,
  "totalResultCount": 8620
}